// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-WwJUeDoxHyoiH6G1OXrOaGzXQhWnSVE',
    appId: '1:242943889892:web:ca8c5dcf487dca040577f1',
    messagingSenderId: '242943889892',
    projectId: 'lawyers-7d828',
    authDomain: 'lawyers-7d828.firebaseapp.com',
    storageBucket: 'lawyers-7d828.appspot.com',
    measurementId: 'G-T2HDEQD6Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoFezj_jdC_bEuyzwUdtGX4Bv1asAAE8A',
    appId: '1:242943889892:android:13d9aaa96bef0a3f0577f1',
    messagingSenderId: '242943889892',
    projectId: 'lawyers-7d828',
    storageBucket: 'lawyers-7d828.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkGEuijtrrNEp0evoh0LZuSwsBiRjZkok',
    appId: '1:242943889892:ios:ba917481674250e70577f1',
    messagingSenderId: '242943889892',
    projectId: 'lawyers-7d828',
    storageBucket: 'lawyers-7d828.appspot.com',
    iosBundleId: 'com.example.lawyerConsultantForLawyers',
  );
}
